"use client";

import { useMemo, useState } from "react";
import { architectureProfiles, capabilityOwners, ecosystemMetrics, frameworkGraph, frameworkPrograms } from "@/data/framework";

export function FrameworkPortfolio() {
  const [query, setQuery] = useState("");
  const profiles = useMemo(() => architectureProfiles.filter((item) => `${item.title} ${item.audience} ${item.requiredCapabilities.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [query]);

  return <div className="space-y-6">
    <section className="overflow-hidden rounded-[28px] border border-emerald-950/10 bg-gradient-to-br from-emerald-950 via-emerald-900 to-slate-950 p-6 text-white shadow-[0_24px_70px_-32px_rgba(6,78,59,.65)] sm:p-8">
      <p className="text-xs font-black uppercase tracking-[.22em] text-emerald-300">PowerChain Foundation</p>
      <div className="mt-4 grid gap-6 xl:grid-cols-[1.3fr_.7fr] xl:items-end"><div><h1 className="max-w-4xl text-3xl font-black tracking-tight sm:text-5xl">PowerChain Engineering Framework</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-emerald-50/80 sm:text-base">A constitutional, standards-based engineering institution coordinating architecture, interoperable protocols, executable specifications and the platform reference implementation.</p></div><div className="grid grid-cols-2 gap-3">{[["4","Programs"],["7","Architecture profiles"],["6","Capability owners"],["8","Traceability nodes"]].map(([value,label]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/10 p-4 backdrop-blur"><p className="text-2xl font-black">{value}</p><p className="mt-1 text-xs text-emerald-100/70">{label}</p></div>)}</div></div>
    </section>

    <section className="grid gap-4 xl:grid-cols-4">{frameworkPrograms.map((program) => <article key={program.id} className="rounded-[22px] border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg dark:border-white/10 dark:bg-slate-950"><div className="flex items-center justify-between"><span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black text-emerald-800 dark:bg-emerald-400/10 dark:text-emerald-200">{program.id}</span><span className="text-[10px] font-bold text-slate-400">{program.cadence}</span></div><h2 className="mt-4 text-lg font-black text-slate-950 dark:text-white">{program.title}</h2><p className="mt-2 text-xs leading-5 text-slate-600 dark:text-slate-300">{program.purpose}</p><div className="mt-4 flex flex-wrap gap-2">{program.owns.slice(0,4).map((item) => <span key={item} className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600 dark:bg-white/10 dark:text-slate-300">{item}</span>)}</div></article>)}</section>

    <section className="rounded-[24px] border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-slate-950 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700 dark:text-emerald-300">Adoption</p><h2 className="mt-2 text-2xl font-black text-slate-950 dark:text-white">Architecture profiles</h2></div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search profiles and capabilities" className="h-11 w-full rounded-xl border border-slate-200 bg-white px-4 text-sm outline-none ring-emerald-500/30 focus:ring-4 dark:border-white/10 dark:bg-slate-900 sm:max-w-sm" /></div><div className="mt-5 grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{profiles.map((profile) => <article key={profile.id} className="rounded-2xl border border-slate-200 p-4 dark:border-white/10"><h3 className="font-black text-slate-950 dark:text-white">{profile.title}</h3><p className="mt-1 text-xs text-slate-500">{profile.audience}</p><p className="mt-4 text-[10px] font-black uppercase tracking-wider text-emerald-700 dark:text-emerald-300">{profile.conformanceProfile}</p><ul className="mt-3 space-y-1.5 text-xs text-slate-600 dark:text-slate-300">{profile.requiredCapabilities.slice(0,4).map((item) => <li key={item}>• {item}</li>)}</ul></article>)}</div></section>

    <section className="grid gap-4 xl:grid-cols-2"><article className="rounded-[24px] border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-slate-950 sm:p-6"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700 dark:text-emerald-300">Accountability</p><h2 className="mt-2 text-xl font-black text-slate-950 dark:text-white">Capability ownership</h2><div className="mt-5 divide-y divide-slate-100 dark:divide-white/10">{capabilityOwners.map((item) => <div key={item.capability} className="grid grid-cols-[1fr_auto] gap-3 py-3"><div><p className="text-sm font-bold text-slate-900 dark:text-white">{item.capability}</p><p className="text-xs text-slate-500">{item.domain} · {item.owner}</p></div><span className="self-center rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold capitalize text-slate-600 dark:bg-white/10 dark:text-slate-300">{item.lifecycle}</span></div>)}</div></article><article className="rounded-[24px] border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-slate-950 sm:p-6"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700 dark:text-emerald-300">Transparency</p><h2 className="mt-2 text-xl font-black text-slate-950 dark:text-white">Ecosystem health</h2><div className="mt-5 space-y-4">{ecosystemMetrics.map((metric) => { const progress = metric.direction === "higher" ? Math.min(metric.value / metric.target * 100, 100) : Math.min(metric.target / metric.value * 100, 100); return <div key={metric.id}><div className="flex items-center justify-between gap-4 text-xs"><span className="font-bold text-slate-700 dark:text-slate-200">{metric.title}</span><span className="font-black text-slate-950 dark:text-white">{metric.value}{metric.unit === "%" ? "%" : ` ${metric.unit}`}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-white/10"><div className="h-full rounded-full bg-emerald-600" style={{ width: `${progress}%` }} /></div></div>})}</div></article></section>

    <section className="rounded-[24px] bg-slate-950 p-5 text-white sm:p-6"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">Knowledge graph</p><h2 className="mt-2 text-xl font-black">Architecture intent to certification</h2><div className="mt-5 grid gap-2 sm:grid-cols-2 xl:grid-cols-8">{frameworkGraph.map((node, index) => <div key={node.id} className="rounded-xl border border-white/10 bg-white/5 p-3"><p className="text-[10px] font-black text-emerald-300">{String(index + 1).padStart(2,"0")} · {node.kind}</p><p className="mt-2 text-xs font-bold text-white">{node.title}</p><p className="mt-2 text-[10px] text-slate-400">{node.id}</p></div>)}</div></section>
  </div>;
}
