"use client";
import{useMemo,useState}from"react";import{carbonCredits,carbonDashboard,carbonProjects,issuanceSeries}from"@/data/carbon";import{BarChart,Bar,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis}from"recharts";
const fmt=new Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:1});
const money=new Intl.NumberFormat("en",{style:"currency",currency:"EUR",maximumFractionDigits:0});
export function CarbonExchangeDashboard(){const[query,setQuery]=useState("");const projects=useMemo(()=>carbonProjects.filter(p=>`${p.name} ${p.country} ${p.owner}`.toLowerCase().includes(query.toLowerCase())),[query]);const kpis=[['Credits issued',fmt.format(carbonDashboard.creditsIssued),'Verified environmental assets'],['Credits traded',fmt.format(carbonDashboard.creditsTraded),'Across spot and bilateral markets'],['Credits retired',fmt.format(carbonDashboard.creditsRetired),'Permanently claimed'],['CO₂ reduced',`${fmt.format(carbonDashboard.co2Reduced)} t`,'Meter and IoT verified'],['ESG score',`${carbonDashboard.esgScore}/100`,'Enterprise sustainability rating'],['Portfolio',money.format(carbonDashboard.portfolioValue),'Current market value']];return <div className="space-y-6">
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{kpis.map(([a,b,c])=><section key={a} className="card p-4"><p className="text-xs font-bold uppercase tracking-wide muted">{a}</p><p className="mt-2 text-2xl font-black">{b}</p><p className="mt-1 text-xs muted">{c}</p></section>)}</div>
<div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><section className="card p-5"><div className="mb-4 flex items-start justify-between"><div><h2 className="text-lg font-black">Issuance and retirement</h2><p className="text-sm muted">Verified monthly carbon asset activity.</p></div><span className="status-badge">Live registry</span></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={issuanceSeries}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip/><Bar dataKey="issued" fill="#0f5a46" radius={[6,6,0,0]}/><Bar dataKey="retired" fill="#86b9a9" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></section>
<section className="card p-5"><h2 className="text-lg font-black">AI carbon intelligence</h2><div className="mt-4 space-y-3">{['Retire 4,200 tonnes from Nordic Solar before the Q3 disclosure deadline.','Baltic Wind credits show a 7.8% pricing advantage versus comparable VCS vintages.','Scope 2 coverage can reach 94% by acquiring 1,850 additional RECs.'].map((x,i)=><article key={x} className="rounded-2xl border p-4"><p className="text-xs font-bold uppercase tracking-wide text-emerald-700">Insight {i+1}</p><p className="mt-1 text-sm leading-6">{x}</p></article>)}</div></section></div>
<div className="grid gap-6 xl:grid-cols-2"><section className="card p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-black">Carbon projects</h2><p className="text-sm muted">Verification-ready renewable and nature projects.</p></div><input className="input sm:w-64" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects worldwide"/></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead><tr className="border-b text-left muted"><th className="py-3">Project</th><th>Country</th><th>Standard</th><th>Verified</th><th>Status</th></tr></thead><tbody>{projects.map(p=><tr key={p.id} className="border-b last:border-0"><td className="py-4 font-bold">{p.name}<span className="block text-xs font-normal muted">{p.owner}</span></td><td>{p.country}</td><td>{p.standard}</td><td>{fmt.format(p.verifiedTonnes)} t</td><td><span className="status-badge">{p.status}</span></td></tr>)}</tbody></table></div></section>
<section className="card p-5"><h2 className="text-lg font-black">Registry and trading activity</h2><p className="text-sm muted">Complete lifecycle visibility from issuance to retirement.</p><div className="mt-4 space-y-3">{carbonCredits.map(c=><article key={c.id} className="flex items-center justify-between rounded-2xl border p-4"><div><p className="font-bold">{c.id}</p><p className="text-xs muted">Vintage {c.vintage} · {fmt.format(c.tonnes)} tCO₂e · {c.currency}</p></div><div className="text-right"><p className="font-black">{c.price.toFixed(2)}</p><span className="status-badge">{c.status}</span></div></article>)}</div></section></div>
<section className="card p-5"><h2 className="text-lg font-black">Compliance and verification pipeline</h2><div className="mt-4 grid gap-3 md:grid-cols-5">{['Meter verified','IoT validated','Methodology checked','Audit approved','Registry issued'].map((x,i)=><div key={x} className="rounded-2xl border p-4"><p className="text-xs font-black text-emerald-700">0{i+1}</p><p className="mt-2 font-bold">{x}</p><p className="mt-1 text-xs muted">Immutable evidence and tenant-scoped audit trail.</p></div>)}</div></section>
</div>}
