import { availableBatchWh, assertPositionBacked, transitionEnergyPosition, type EnergyBatch, type EnergyPosition, type EnergyRetirement, type EnergyRetirementReason } from "@powerchain/energy-core";
import { allocateRepresentation, assertEnergyRwaAccess, buildPet20EnergyMetadata, validateRegistry, type ChainRepresentation, type EnergyProvenanceMetadata, type EnergyRwaAccessContext, type EnergyRwaDenomination, type TenantScopedEnergyRwa } from "@powerchain/energy-rwa";
import { matchLocalOrders, type EnergyOrder, type GridConstraint } from "@powerchain/local-energy-market";

export class LocalEnergyService {
  readonly batches=new Map<string,EnergyBatch>(); readonly positions=new Map<string,EnergyPosition>(); readonly rwaAssets=new Map<string,TenantScopedEnergyRwa>(); readonly orders=new Map<string,EnergyOrder>(); readonly retirements=new Map<string,EnergyRetirement>();
  putBatch(batch:EnergyBatch){availableBatchWh(batch);this.batches.set(batch.id,batch);return batch;}
  putPosition(position:EnergyPosition){const batch=this.batches.get(position.energyBatchId);if(!batch)throw new Error("ENERGY_BATCH_NOT_FOUND");assertPositionBacked(position,batch);this.positions.set(position.id,position);return position;}
  createEnergyRwa(args:{id:string;tenantId:string;organizationId:string;companyId?:string;positionId:string;denomination:EnergyRwaDenomination;provenance:EnergyProvenanceMetadata},context:EnergyRwaAccessContext){
    if(context.tenantId!==args.tenantId)throw new Error("TENANT_SCOPE_DENIED"); if(context.organizationId&&context.organizationId!==args.organizationId)throw new Error("ORGANIZATION_SCOPE_DENIED");
    const position=this.positions.get(args.positionId);if(!position)throw new Error("ENERGY_POSITION_NOT_FOUND");if(position.tenantId&&position.tenantId!==args.tenantId)throw new Error("POSITION_TENANT_SCOPE_DENIED");if(position.organizationId&&position.organizationId!==args.organizationId)throw new Error("POSITION_ORGANIZATION_SCOPE_DENIED");if(position.companyId&&args.companyId&&position.companyId!==args.companyId)throw new Error("POSITION_COMPANY_SCOPE_DENIED"); const batch=this.batches.get(position.energyBatchId);if(!batch)throw new Error("ENERGY_BATCH_NOT_FOUND"); assertPositionBacked(position,batch);
    const {metadata,digest}=buildPet20EnergyMetadata({tenantId:args.tenantId,organizationId:args.organizationId,denomination:args.denomination,position,batch,provenance:args.provenance});
    const now=new Date(); const asset:TenantScopedEnergyRwa={id:args.id,tenantId:args.tenantId,organizationId:args.organizationId,...(args.companyId?{companyId:args.companyId}:{}),position,metadata,metadataDigest:digest,registry:{energyPositionId:position.id,canonicalWh:position.amountWh,representations:[]},createdAt:now,updatedAt:now}; this.rwaAssets.set(asset.id,asset);return asset;
  }
  getEnergyRwa(id:string,context:EnergyRwaAccessContext){const asset=this.rwaAssets.get(id);if(!asset)throw new Error("ENERGY_RWA_NOT_FOUND");assertEnergyRwaAccess(context,asset);return asset;}
  listEnergyRwa(context:EnergyRwaAccessContext){return [...this.rwaAssets.values()].filter((asset)=>{try{assertEnergyRwaAccess(context,asset);return true;}catch{return false;}});}
  addRepresentation(id:string,representation:ChainRepresentation,context:EnergyRwaAccessContext){const asset=this.getEnergyRwa(id,context);asset.registry=allocateRepresentation(asset.registry,representation);validateRegistry(asset.registry);asset.updatedAt=new Date();return asset;}
  retireEnergyRwa(id:string,args:{retirementId:string;amountWh:bigint;reason:EnergyRetirementReason;tradeId?:string;settlementId?:string;receiptReference?:string},context:EnergyRwaAccessContext){const asset=this.getEnergyRwa(id,context);if(args.amountWh!==asset.position.amountWh)throw new Error("PARTIAL_RETIREMENT_REQUIRES_POSITION_SPLIT");asset.position={...asset.position,state:transitionEnergyPosition(asset.position.state,"RETIRED")};asset.registry={...asset.registry,representations:asset.registry.representations.map((r)=>({...r,state:"RETIRED" as const}))};const retirement:EnergyRetirement={id:args.retirementId,energyPositionId:asset.position.id,amountWh:args.amountWh,reason:args.reason,...(args.tradeId?{tradeId:args.tradeId}:{}),...(args.settlementId?{settlementId:args.settlementId}:{}),...(args.receiptReference?{receiptReference:args.receiptReference}:{}),retiredAt:new Date()};this.retirements.set(retirement.id,retirement);asset.updatedAt=new Date();return{asset,retirement};}
  createOrder(order:EnergyOrder){if(order.amountWh<=0n||order.remainingWh<=0n)throw new Error("ORDER_AMOUNT_MUST_BE_POSITIVE");this.orders.set(order.id,order);return order;}
  match(sellerOrderId:string,buyerOrderId:string,constraint:GridConstraint){const seller=this.orders.get(sellerOrderId),buyer=this.orders.get(buyerOrderId);if(!seller||!buyer)throw new Error("ORDER_NOT_FOUND");return matchLocalOrders(seller,buyer,constraint);}
}
export const localEnergyService=new LocalEnergyService();
