"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, Fingerprint, LockKeyhole, RefreshCw, Scale, ShieldCheck, UserCheck, WalletCards, Zap } from "lucide-react";
import { Shell } from "@/components/shell";
import { fetchDigitalEnergyOverview, wh } from "./api";
import type { DigitalEnergyOverviewPayload } from "./types";

type FormMode="CREATE_DELIVERY"|"RECORD_DELIVERY"|"RECONCILE"|"PREPARE_SETTLEMENT"|"TRANSITION_SETTLEMENT";
async function post(path:string,body:unknown){const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json","idempotency-key":`ops_${crypto.randomUUID()}`},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload?.error?.message??payload?.error?.code??"Digital Energy operation failed");return payload}

export function EnergyOperationsWorkspace(){
  const[data,setData]=useState<DigitalEnergyOverviewPayload|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[mode,setMode]=useState<FormMode>("CREATE_DELIVERY");const[executing,setExecuting]=useState(false);const[result,setResult]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{setData((await fetchDigitalEnergyOverview()).data);setError(null)}catch(cause){setError(cause instanceof Error?cause.message:"Energy operations unavailable")}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const operations=data?.operations;const summary=operations?.summary;const controls=operations?.controls;
  const positions=data?.positions??[];const reservations=(data?.rwas??[]).flatMap(rwa=>rwa.reservations.filter(item=>item.state==="ACTIVE").map(item=>({...item,positionId:rwa.position.id})));const deliveries=operations?.deliveries??[];const reconciliations=operations?.reconciliations??[];const settlements=operations?.settlements??[];
  const reconciledDeliveries=deliveries.filter(item=>item.state==="RECONCILED");
  const formKey=`${mode}:${deliveries.length}:${reconciliations.length}:${settlements.length}`;
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setExecuting(true);setResult(null);const values=Object.fromEntries(new FormData(event.currentTarget).entries());try{
    if(mode==="CREATE_DELIVERY"){const reservation=reservations.find(item=>item.id===String(values.reservationId));if(!reservation)throw new Error("Select an active Energy Reservation");await post("/api/v1/digital-energy/deliveries",{id:`delivery_${crypto.randomUUID()}`,positionId:reservation.positionId,reservationId:reservation.id,committedWh:String(values.committedWh),intervalStart:String(values.intervalStart),intervalEnd:String(values.intervalEnd)})}
    if(mode==="RECORD_DELIVERY")await post(`/api/v1/digital-energy/deliveries/${encodeURIComponent(String(values.deliveryId))}/record`,{deliveredWh:String(values.deliveredWh),meterEvidenceRoot:String(values.meterEvidenceRoot)});
    if(mode==="RECONCILE")await post(`/api/v1/digital-energy/deliveries/${encodeURIComponent(String(values.deliveryId))}/reconcile`,{reconciliationId:`recon_${crypto.randomUUID()}`,toleranceWh:String(values.toleranceWh),approve:values.approve==="true"});
    if(mode==="PREPARE_SETTLEMENT")await post("/api/v1/digital-energy/settlements",{settlementId:`settlement_${crypto.randomUUID()}`,deliveryId:String(values.deliveryId),reconciliationId:String(values.reconciliationId),asset:String(values.asset),network:String(values.network),amountMinor:String(values.amountMinor)});
    if(mode==="TRANSITION_SETTLEMENT")await post(`/api/v1/digital-energy/settlements/${encodeURIComponent(String(values.settlementId))}/transition`,{state:String(values.state),reference:String(values.reference||"")||undefined});
    setResult("Operation completed and audited.");await load();
  }catch(cause){setResult(cause instanceof Error?cause.message:"Operation failed")}finally{setExecuting(false)}}
  return <Shell><div className="operations-workspace">
    <header className="workspace-hero"><div><span className="eyebrow">Energy operations</span><h1>Delivery, reconciliation & settlement</h1><p>Commit verified energy, record meter-evidenced delivery, reconcile variance, then prepare and confirm financial settlement. Each stage is explicit and auditable.</p></div><div className="workspace-hero-actions"><span>{data?.summary.dataMode??"CHECKING"}</span><button onClick={()=>void load()} disabled={loading}><RefreshCw className={loading?"animate-spin":""}/>Refresh</button></div></header>
    {error&&<div className="digital-energy-error"><ShieldCheck/><div><strong>Operations unavailable</strong><span>{error}</span></div></div>}
    <section className="operations-metric-grid"><article><span>Committed</span><strong>{summary?wh(summary.committedWh):"—"}</strong></article><article><span>Delivered</span><strong>{summary?wh(summary.deliveredWh):"—"}</strong></article><article><span>Reconciliation review</span><strong>{summary?.reviewRequiredReconciliations??0}</strong></article><article><span>Approval queue</span><strong>{summary?.pendingSettlementApprovals??0}</strong></article><article><span>Outbox backlog</span><strong>{controls?.pendingOutboxEvents??0}</strong></article></section>
    <section className="dashboard-panel institutional-control-panel"><div className="dashboard-card-head"><div><span className="eyebrow">Canonical operating flow</span><h2>Physical completion before controlled financial execution</h2></div><Link href="/digital-energy/controls">Open institutional controls</Link></div><div className="operations-flow"><span>COMMIT</span><ArrowRight/><span>DELIVER</span><ArrowRight/><span>RECONCILE</span><ArrowRight/><span>REVIEW HASH</span><ArrowRight/><span>APPROVE</span><ArrowRight/><span>SETTLE</span><ArrowRight/><span>RETIRE</span></div><div className="institutional-control-flow"><span><Fingerprint/>Exact SHA-256 review hash</span><ArrowRight/><span><UserCheck/>{controls?.settlementApprovalsRequired??2} distinct checker approvals</span><ArrowRight/><span><LockKeyhole/>Maker-checker enforced</span></div><div className="operations-principles"><span>Meter evidence required for delivery</span><span>Variance is explicit</span><span>Approval does not prove delivery</span><span>Confirmation ≠ electricity</span></div></section>
    <section className="digital-energy-grid">
      <article className="dashboard-panel"><div className="dashboard-card-head"><div><span className="eyebrow">Delivery ledger</span><h2>Delivery lifecycle</h2></div><Zap className="h-5 w-5 text-emerald-700"/></div><div className="operations-timeline">{deliveries.map(item=><div className="operation-row" key={item.id}><div><strong>{item.id}</strong><small>{item.energyPositionId}</small></div><div><span className={`operation-state ${item.state.toLowerCase().replaceAll('_','-')}`}>{item.state}</span></div><div><strong>{wh(item.committedWh)}</strong><small>committed</small></div><div><strong>{wh(item.deliveredWh)}</strong><small>{item.meterEvidenceRoot?"meter evidence":"awaiting evidence"}</small></div></div>)}{!deliveries.length&&<p>No deliveries.</p>}</div></article>
      <article className="dashboard-panel"><div className="dashboard-card-head"><div><span className="eyebrow">Financial rail</span><h2>Settlement lifecycle</h2></div><WalletCards className="h-5 w-5 text-emerald-700"/></div><div className="settlement-rail">{settlements.map(item=><article key={item.id}><div><strong>{item.asset} · {item.network}</strong><small>{item.id} · delivery {item.deliveryId}</small>{item.reference&&<code>{item.reference}</code>}</div><span className={`operation-state ${item.state.toLowerCase()}`}>{item.state}</span></article>)}{!settlements.length&&<p>No settlements.</p>}</div></article>
    </section>
    <section className="dashboard-panel"><div className="dashboard-card-head"><div><span className="eyebrow">Review-first mutations</span><h2>Operations console</h2></div><ShieldCheck className="h-5 w-5 text-emerald-700"/></div><div className="flex flex-wrap gap-2 mb-4">{(["CREATE_DELIVERY","RECORD_DELIVERY","RECONCILE","PREPARE_SETTLEMENT","TRANSITION_SETTLEMENT"] as FormMode[]).map(item=><button key={item} type="button" onClick={()=>setMode(item)} className={`position-state ${mode===item?"!bg-emerald-700 !text-white":""}`}>{item.replaceAll('_',' ')}</button>)}</div><OperationsForm key={formKey} mode={mode} positions={positions} reservations={reservations} deliveries={deliveries} reconciliations={reconciliations} settlements={settlements} reconciledDeliveries={reconciledDeliveries} executing={executing} onSubmit={submit}/>{result&&<p className="safe-action-note">{result}</p>}</section>
  </div></Shell>
}

function OperationsForm({mode,positions,reservations,deliveries,reconciliations,settlements,reconciledDeliveries,executing,onSubmit}:{mode:FormMode;positions:DigitalEnergyOverviewPayload["positions"];reservations:Array<{id:string;amountWh:string;purpose:string;state:string;positionId:string}>;deliveries:NonNullable<DigitalEnergyOverviewPayload["operations"]>["deliveries"];reconciliations:NonNullable<DigitalEnergyOverviewPayload["operations"]>["reconciliations"];settlements:NonNullable<DigitalEnergyOverviewPayload["operations"]>["settlements"];reconciledDeliveries:NonNullable<DigitalEnergyOverviewPayload["operations"]>["deliveries"];executing:boolean;onSubmit:(event:React.FormEvent<HTMLFormElement>)=>void}){
 const now=new Date();const later=new Date(now.getTime()+60*60*1000);const eligibleReconciliations=reconciliations.filter(item=>item.state==="RECONCILED");
 return <form className="operations-action-form" onSubmit={onSubmit}>
  {mode==="CREATE_DELIVERY"&&<><label>Energy reservation<select name="reservationId" required>{reservations.map(r=><option key={r.id} value={r.id}>{r.id} · {r.positionId} · {wh(r.amountWh)}</option>)}</select></label><label>Committed Wh<input name="committedWh" defaultValue="1000" inputMode="numeric" required/></label><label>Interval start<input name="intervalStart" type="datetime-local" defaultValue={now.toISOString().slice(0,16)} required/></label><label>Interval end<input name="intervalEnd" type="datetime-local" defaultValue={later.toISOString().slice(0,16)} required/></label></>}
  {mode==="RECORD_DELIVERY"&&<><label>Delivery<select name="deliveryId" required>{deliveries.filter(d=>["COMMITTED","DELIVERING"].includes(d.state)).map(d=><option key={d.id} value={d.id}>{d.id} · {wh(d.committedWh)}</option>)}</select></label><label>Delivered Wh<input name="deliveredWh" defaultValue="986" inputMode="numeric" required/></label><label>Meter evidence root<input name="meterEvidenceRoot" defaultValue={`meter_${crypto.randomUUID()}`} required/></label></>}
  {mode==="RECONCILE"&&<><label>Delivered record<select name="deliveryId" required>{deliveries.filter(d=>["DELIVERED","DISPUTED"].includes(d.state)).map(d=><option key={d.id} value={d.id}>{d.id} · {wh(d.deliveredWh)}</option>)}</select></label><label>Tolerance Wh<input name="toleranceWh" defaultValue="25" inputMode="numeric" required/></label><label>Approval<select name="approve" defaultValue="true"><option value="true">Approve if reviewed</option><option value="false">Calculate only</option></select></label></>}
  {mode==="PREPARE_SETTLEMENT"&&<><label>Reconciled delivery<select name="deliveryId" required>{reconciledDeliveries.map(d=><option key={d.id} value={d.id}>{d.id}</option>)}</select></label><label>Reconciliation<select name="reconciliationId" required>{eligibleReconciliations.map(r=><option key={r.id} value={r.id}>{r.id} · variance {r.varianceWh} Wh</option>)}</select></label><label>Settlement asset<select name="asset"><option>EURC</option><option>USDC</option><option>FIAT_EUR</option></select></label><label>Network<select name="network"><option>SOLANA</option><option>OFFCHAIN</option></select></label><label>Amount minor units<input name="amountMinor" defaultValue="17" inputMode="numeric" required/></label></>}
  {mode==="TRANSITION_SETTLEMENT"&&<><label>Settlement<select name="settlementId" required>{settlements.filter(s=>!["RECONCILED","CANCELLED"].includes(s.state)).map(s=><option key={s.id} value={s.id}>{s.id} · {s.state}</option>)}</select></label><label>Next state<select name="state"><option>SUBMITTED</option><option>CONFIRMED</option><option>RECONCILED</option><option>FAILED</option><option>CANCELLED</option></select></label><label>Transaction/reference<input name="reference" placeholder="optional network or ledger reference"/></label></>}
  <button type="submit" disabled={executing}>{executing?"Executing…":"Review & execute with Idempotency-Key"}<CheckCircle2 className="inline h-4 w-4 ml-2"/></button>
 </form>
}
