export const ROUTES = {
  home: "/",
  apiBase: "/api/v1",
  signin: "/auth/signin",
  signup: "/auth/signup",
  pricing: "/pricing",
  wallet: "/wallet",
  account: "/account",
  transactions: "/transactions",
  profile: "/settings",
  integrations: "/settings/integrations",
  cetus: "/settings/integrations?provider=cetus",
  users: "/admin/users",
  analytics: "/analytics",
  marketplace: "/marketplace",
  products: "/products",
  exchange: "/exchange",
  carbonExchange: "/carbon",
  intelligence: "/intelligence",
  proofOfEnergy: "/proof-of-energy",
  digitalTwins: "/digital-twins",
  ecosystem: "/ecosystem",
  platform: "/platform",
  architecture: "/architecture",
  standards: "/standards",
  framework: "/framework",
  developer: "/developer",
  docs: "/docs",
  docsLegal: "/docs/legal",
  docsArchitecture: "/docs/architecture",
  docsApi: "/docs/api",
  docsAi: "/docs/ai",
  docsTokens: "/docs/tokens",
  tokenization: "/tokenization",
  tokenPwrc: "/tokens/pwrc",
  tokenWpwrc: "/tokens/wpwrc",
  tokenCrt: "/tokens/crt",
  blockchain: "/blockchain",
  leaderboard: "/leaderboard",
  legacyExchange: "/energy-exchange",
  localEnergy: "/local-energy",
  localEnergyMarketplace: "/local-energy/marketplace",
  localEnergyGrid: "/local-energy/grid",
  localEnergyDevices: "/local-energy/devices",
  localEnergySettlement: "/local-energy/settlement",
  p2pEnergy: "/p2p-energy",
  renewables: "/renewables",
  energy: "/energy",
  digitalEnergy: "/digital-energy",
  energyRwa: "/energy-rwa",
  assetGraph: "/asset-graph",
  energyOperations: "/energy-operations",
  digitalEnergyTwin: "/digital-energy/twin",
  digitalEnergyControls: "/digital-energy/controls",
  energySolar: "/energy/solar",
  energyWind: "/energy/wind",
  energyStorage: "/energy/storage",
  energyForecast: "/energy/forecast",
  smartGridMap: "/map",
  smartMeters: "/metering/smart-meters",
  depin: "/depin",
  copilot: "/copilot",
  copilotActionCenter: "/copilot/action-center",
  copilotArchitecture: "/copilot/architecture",
  copilotAgents: "/copilot/agents",
  copilotAgentBuilder: "/copilot/agents/builder",
  copilotSkills: "/copilot/skills",
  copilotPrompts: "/copilot/prompts",
  copilotSettings: "/copilot/settings",
  chat: "/chat",
  aiDashboard: "/dashboard/ai",
  aiChat: "/dashboard/ai/chat",
  aiAgents: "/dashboard/ai/agents",
  aiPrompts: "/dashboard/ai/prompts",
  aiModels: "/dashboard/ai/models",
  aiLora: "/dashboard/ai/lora",
  aiMemory: "/dashboard/ai/memory",
  aiProviders: "/dashboard/ai/providers",
  aiUsage: "/dashboard/ai/usage",
  aiCredits: "/dashboard/ai/credits",
  aiSettings: "/dashboard/ai/settings",
  hardwares: "/hardwares",
  deviceProducts: "/products/devices",
  firmwares: "/firmwares",
  portfolio: "/portfolio",
  billing: "/billing",
  crm: "/crm",
  participants: "/organizations/participants",
  organization: "/settings/organization",
  projects: "/projects",
  crowdfunding: "/crowdfunding",
  caseStudies: "/case-studies",
  governance: "/governance",
  certification: "/certification",
  checkout: "/checkout",
  protocols: "/protocols",
  exploreProjects: "/explore/projects",
} as const;

export const routes = {
  ...ROUTES,
  overview: ROUTES.home,
  assets: ROUTES.portfolio,
  map: ROUTES.smartGridMap,
  alerts: ROUTES.analytics,
  incidents: ROUTES.analytics,
  carbon: ROUTES.portfolio,
  treasury: ROUTES.wallet,
  plugins: ROUTES.integrations,
  admin: ROUTES.users,
} as const;

export type RouteKey = keyof typeof ROUTES;
export type AppRoute = (typeof ROUTES)[RouteKey];

export const LEGACY_REDIRECTS = {
  "/tokens/cct": ROUTES.tokenCrt,
  "/login": ROUTES.signin,
  "/profile": ROUTES.profile,
  "/energy-market": ROUTES.exchange,
  "/p2p-energy": ROUTES.localEnergyMarketplace,
  "/integration": ROUTES.integrations,
  "/ai": ROUTES.copilot,
  "/chat": ROUTES.copilot,
  "/intelligence": ROUTES.copilot,
} as const;

export function isAppRoute(value: unknown): value is AppRoute {
  return typeof value === "string" && Object.values(ROUTES).includes(value as AppRoute);
}
