import { notFound } from "next/navigation";
import { Shell } from "@/components/shell";
import { fundingProjects } from "@/data/projects";
import { ButtonLink } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

export function generateStaticParams(){return fundingProjects.flatMap((project)=>[{id:project.id},{id:project.slug}]);}
export default async function ExploreProjectPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params;
  const project=fundingProjects.find((item)=>item.id.toLowerCase()===id.toLowerCase()||item.slug===id);
  if(!project) notFound();
  const funded=Math.min(100,Math.round(project.raised/project.goal*100));
  return <Shell><div className="content-container"><article className="overflow-hidden rounded-[28px] border border-[var(--border)] bg-[var(--surface)] shadow-[0_24px_70px_rgba(15,23,42,.08)]"><header className="project-hero relative min-h-[300px] p-7 text-white sm:p-10"><div className="absolute inset-0 bg-gradient-to-r from-[#073f31]/95 via-[#0b5844]/80 to-transparent"/><div className="relative max-w-3xl"><div className="flex flex-wrap gap-2"><Badge variant="dark-green">{project.assetType}</Badge><Badge variant="warning">MVP financing preview</Badge></div><p className="mt-5 text-xs font-semibold uppercase tracking-[.2em] text-emerald-100">{project.id} · {project.slug}</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">{project.title}</h1><p className="mt-4 max-w-2xl leading-7 text-white/80">{project.summary}</p></div></header><div className="grid gap-7 p-6 lg:grid-cols-[1fr_22rem] lg:p-9"><section className="space-y-6"><div><h2 className="text-xl font-semibold">Project overview</h2><p className="mt-3 max-w-3xl leading-7 text-[var(--muted)]">This identified renewable project combines milestone financing, digital-twin monitoring, Proof of Energy verification and tokenized impact reporting. Commercial terms remain subject to verification and project documentation.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Location" value={project.location??"PowerChain Network"}/><Stat label="Capacity" value={project.capacity??"Pending"}/><Stat label="Backers" value={project.backers.toLocaleString()}/><Stat label="Days left" value={String(project.daysLeft)}/></div><div className="rounded-[22px] border border-[var(--border)] bg-black/[.02] p-5 dark:bg-white/[.03]"><h3 className="font-semibold">Verification roadmap</h3><ol className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><li>1. Asset and owner verification</li><li>2. Smart-meter onboarding</li><li>3. Grid and permitting review</li><li>4. Milestone financing release</li></ol></div></section><aside className="h-fit rounded-[22px] border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm lg:sticky lg:top-24"><span className="text-sm text-[var(--muted)]">Raised</span><strong className="mt-1 block text-3xl font-semibold">€{project.raised.toLocaleString()}</strong><p className="mt-1 text-sm text-[var(--muted)]">of €{project.goal.toLocaleString()}</p><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-black/10 dark:bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-emerald-700 to-emerald-500" style={{width:`${funded}%`}}/></div><p className="mt-2 text-right text-sm font-semibold text-emerald-700">{funded}% funded</p><ButtonLink href={`/checkout?project=${encodeURIComponent(project.slug)}`} className="mt-5 w-full">Review participation</ButtonLink><p className="mt-3 text-xs leading-5 text-[var(--muted)]">No investment or return is guaranteed. This page is an MVP project preview.</p></aside></div></article></div></Shell>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-[18px] border border-[var(--border)] p-4"><span className="text-xs text-[var(--muted)]">{label}</span><strong className="mt-1 block text-base font-semibold">{value}</strong></div>}
