export const POWERCHAIN_MAPPER_LOCAL_ENERGY_LAYERS = [
  "Power Plants",
  "Wind Farms",
  "Solar Farms",
  "Hydro",
  "Substations",
  "Transformers",
  "Feeders",
  "Grid Areas",
  "Connection Points",
  "Homes",
  "Batteries",
  "EV Chargers",
  "Smart Meters",
  "Energy Communities",
  "VPPs",
  "Market Zones",
  "Congestion",
  "Outages",
  "Renewable Generation",
  "Energy Flow",
] as const;
