import { clientEnvironmentSchema } from "./schema";

/** Browser-safe environment values. Never add secrets to this object. */
export const clientEnv = clientEnvironmentSchema.parse({
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
  NEXT_PUBLIC_AI_ENABLED: process.env.NEXT_PUBLIC_AI_ENABLED,
  NEXT_PUBLIC_SOLANA_CLUSTER: process.env.NEXT_PUBLIC_SOLANA_CLUSTER,
  NEXT_PUBLIC_SOLANA_DEVNET_RPC_URL: process.env.NEXT_PUBLIC_SOLANA_DEVNET_RPC_URL,
  NEXT_PUBLIC_SOLANA_MAINNET_RPC_URL: process.env.NEXT_PUBLIC_SOLANA_MAINNET_RPC_URL,
  NEXT_PUBLIC_SOLANA_CUSTOM_RPC_URL: process.env.NEXT_PUBLIC_SOLANA_CUSTOM_RPC_URL,
  NEXT_PUBLIC_POWERCHAIN_PROGRAM_ID_DEVNET: process.env.NEXT_PUBLIC_POWERCHAIN_PROGRAM_ID_DEVNET,
  NEXT_PUBLIC_POWERCHAIN_PROGRAM_ID_MAINNET: process.env.NEXT_PUBLIC_POWERCHAIN_PROGRAM_ID_MAINNET,
  NEXT_PUBLIC_SUI_NETWORK: process.env.NEXT_PUBLIC_SUI_NETWORK,
  NEXT_PUBLIC_SUI_DEVNET_RPC_URL: process.env.NEXT_PUBLIC_SUI_DEVNET_RPC_URL,
  NEXT_PUBLIC_SUI_TESTNET_RPC_URL: process.env.NEXT_PUBLIC_SUI_TESTNET_RPC_URL,
  NEXT_PUBLIC_SUI_MAINNET_RPC_URL: process.env.NEXT_PUBLIC_SUI_MAINNET_RPC_URL,
  NEXT_PUBLIC_SUI_CUSTOM_RPC_URL: process.env.NEXT_PUBLIC_SUI_CUSTOM_RPC_URL
});
