"use client";
import {createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode} from "react";
import {getWalletProviderAdapter,walletProviderAdapters} from "@/lib/wallet/providers";
import type {ConnectedWallet,WalletNetwork,WalletSnapshot} from "@/types/wallet/provider";
import {isSolanaAddress} from "@/types/validate";
const STORAGE_KEY="powerchain.wallet.v3";
type WalletContextValue={wallet:ConnectedWallet|null;snapshot:WalletSnapshot|null;address:string|null;provider:string|null;network:WalletNetwork|null;isOpen:boolean;isLoading:boolean;error:string|null;open:()=>void;close:()=>void;connectProvider:(providerId:string)=>Promise<void>;connectAddress:(address:string,network:WalletNetwork)=>Promise<void>;refresh:()=>Promise<void>;disconnect:()=>Promise<void>};
const WalletContext=createContext<WalletContextValue|null>(null);
function isValidAddress(address:string,network:WalletNetwork){if(network==="solana")return isSolanaAddress(address);if(network==="sui")return /^0x[a-fA-F0-9]{64}$/.test(address);return /^0x[a-fA-F0-9]{40}$/.test(address)}
export function WalletProvider({children}:{children:ReactNode}){const[wallet,setWallet]=useState<ConnectedWallet|null>(null);const[snapshot,setSnapshot]=useState<WalletSnapshot|null>(null);const[isOpen,setOpen]=useState(false);const[isLoading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);
  const loadSnapshot=useCallback(async(next:ConnectedWallet)=>{if(next.network!=="solana"){setSnapshot({address:next.address,network:next.network,assets:[],state:"degraded",observedAt:new Date().toISOString()});return}const response=await fetch(`/api/v1/wallet-data?address=${encodeURIComponent(next.address)}`,{cache:"no-store"});if(!response.ok)throw new Error("Wallet connected, but account data is currently unavailable.");const body=await response.json();setSnapshot({...body.data,network:next.network,state:"available",observedAt:new Date().toISOString()})},[]);
  useEffect(()=>{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return;try{const saved=JSON.parse(raw) as ConnectedWallet;if(isValidAddress(saved.address,saved.network)){setWallet(saved);void loadSnapshot(saved).catch((cause)=>setError(cause instanceof Error?cause.message:"Wallet data unavailable"))}}catch{localStorage.removeItem(STORAGE_KEY)}},[loadSnapshot]);
  const persist=useCallback(async(next:ConnectedWallet)=>{setLoading(true);setError(null);try{const response=await fetch("/api/v1/wallet",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({address:next.address,network:next.network,provider:next.provider})});if(!response.ok)throw new Error("Wallet connection could not be registered.");localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setWallet(next);await loadSnapshot(next);setOpen(false)}finally{setLoading(false)}},[loadSnapshot]);
  const connectProvider=useCallback(async(providerId:string)=>{const adapter=getWalletProviderAdapter(providerId);if(!adapter)throw new Error("Unsupported wallet provider.");const address=await adapter.connect();if(!isValidAddress(address,adapter.network))throw new Error(`Invalid ${adapter.network} wallet address.`);await persist({address,network:adapter.network,provider:adapter.name,connectedAt:new Date().toISOString()})},[persist]);
  const connectAddress=useCallback(async(address:string,network:WalletNetwork)=>{const normalized=address.trim();if(!isValidAddress(normalized,network))throw new Error(`Enter a valid ${network} wallet address.`);await persist({address:normalized,network,provider:"Watch-only",connectedAt:new Date().toISOString()})},[persist]);
  const refresh=useCallback(async()=>{if(!wallet)return;setLoading(true);setError(null);try{await loadSnapshot(wallet)}catch(cause){setError(cause instanceof Error?cause.message:"Wallet data unavailable")}finally{setLoading(false)}},[wallet,loadSnapshot]);
  const disconnect=useCallback(async()=>{if(wallet)await walletProviderAdapters.find((adapter)=>adapter.name===wallet.provider)?.disconnect?.();localStorage.removeItem(STORAGE_KEY);setWallet(null);setSnapshot(null);setError(null)},[wallet]);
  const value=useMemo<WalletContextValue>(()=>({wallet,snapshot,address:wallet?.address??null,provider:wallet?.provider??null,network:wallet?.network??null,isOpen,isLoading,error,open:()=>setOpen(true),close:()=>setOpen(false),connectProvider,connectAddress,refresh,disconnect}),[wallet,snapshot,isOpen,isLoading,error,connectProvider,connectAddress,refresh,disconnect]);return <WalletContext.Provider value={value}>{children}</WalletContext.Provider>}
export function useWallet(){const value=useContext(WalletContext);if(!value)throw new Error("useWallet must be used inside WalletProvider");return value}
