export const POWER_GRID_LOCAL_ENERGY_CAPABILITIES = [
  "GRID_AREAS",
  "SUBSTATIONS",
  "TRANSFORMERS",
  "FEEDERS",
  "CONNECTION_POINTS",
  "CONGESTION",
  "IMPORT_EXPORT_CONSTRAINTS",
  "DEMAND_RESPONSE",
  "DISTRIBUTED_ENERGY_RESOURCES",
  "VIRTUAL_POWER_PLANTS",
  "MICROGRIDS",
] as const;
