"use client";
import { formatEnergy } from "@powerchain/energy-core";
import { DataTable, DataValue, EmptyState, InlineNotice, PageHeader, Panel, Skeleton, StatusBadge, TableToolbar } from "@powerchain/ui";
import { useEnergyResource } from "../../../components/use-energy-resource";
type Reservation={id:string;positionId:string;amountWh:string;orderId?:string|null;createdAt:string};
function energy(v:string){try{return formatEnergy(BigInt(v));}catch{return{value:"—",unit:""};}}
function short(v:string){return v.length>14?`${v.slice(0,7)}…${v.slice(-4)}`:v;}
export default function MarketsPage(){const data=useEnergyResource<{items:Reservation[]}>("/api/v1/energy-reservations");return <main className="pc-page ems-page"><PageHeader eyebrow="EMS · Markets" title="Markets" description="Market commitments are shown only where they reserve verified physical-energy positions; market price/order-book data requires a dedicated market service." action={<StatusBadge tone="info">RESERVATION VIEW</StatusBadge>}/><InlineNotice title="Market and physical delivery remain separate" tone="info" icon="market">A reservation prevents double commitment of energy backing. It does not prove delivery, financial settlement or blockchain confirmation.</InlineNotice><div className="pc-grid ems-grid-gap"><Panel className="pc-span-12" eyebrow="Committed supply" title="Energy reservations" description="Existing economic holds against Energy Positions.">{data.loading?<Skeleton lines={5}/>:<><TableToolbar title="Reservations" count={data.data?.items.length??0}/><DataTable rows={data.data?.items??[]} rowKey={r=>r.id} columns={[
{key:"reservation",header:"Reservation",cell:r=><DataValue value={short(r.id)} meta={`Position ${short(r.positionId)}`}/>},{key:"order",header:"Order",cell:r=><DataValue value={r.orderId?short(r.orderId):"—"} meta={r.orderId?"External/order reference":"Not linked"}/>},{key:"quantity",header:"Quantity",align:"right",cell:r=>{const v=energy(r.amountWh);return <DataValue value={`${v.value} ${v.unit}`}/>;}},{key:"created",header:"Created",cell:r=><DataValue value={new Date(r.createdAt).toLocaleString()}/>}]} empty={<EmptyState icon="market" title="No energy reservations" description="Market commitments appear after a verified Energy Position is reserved through an authorized economic workflow."/>}/></>}</Panel></div></main>}
