"use client";
import { Heart, MapPin, ShieldCheck, Sparkles, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { usePreferences } from "@/context/preferences-context";
import { useState } from "react";
export type EnergyListing={id:string;slug:string;name:string;location:string;source:string;price:number;available:number;verified:boolean;distanceKm?:number;carbonIntensity?:number;delivery?:string;rating?:number};
export function ListingCard({listing,onReview}:{listing:EnergyListing;onReview?:(listing:EnergyListing)=>void}){
 const {formatMoney,formatDistance}=usePreferences();
 const [watched,setWatched]=useState(false);
 const sourceClass=listing.source.toLowerCase()==="wind"?"from-slate-950 via-emerald-950 to-sky-900":listing.source.toLowerCase()==="hydro"?"from-cyan-950 via-emerald-950 to-blue-900":"from-emerald-950 via-emerald-800 to-amber-700";
 return <article className="market-card group overflow-hidden"><div className={`relative h-48 overflow-hidden bg-gradient-to-br ${sourceClass} p-4 text-white`}><div className="flex items-start justify-between"><Badge className="border-white/20 bg-white/15 text-white backdrop-blur-md">{listing.source}</Badge><button type="button" onClick={()=>setWatched((value)=>!value)} aria-pressed={watched} className="grid h-9 w-9 place-items-center rounded-full bg-white/15 backdrop-blur" aria-label={watched?"Remove from watchlist":"Add to watchlist"}><Heart className={`h-4 w-4 ${watched?"fill-current":""}`}/></button></div><div aria-hidden className="absolute -right-8 top-10 h-32 w-32 rounded-full bg-white/10 blur-2xl"/><div aria-hidden className="absolute bottom-0 left-0 h-20 w-full bg-[linear-gradient(transparent,rgba(3,30,24,.72))]"/><div className="absolute inset-x-4 bottom-4 rounded-2xl border border-white/20 bg-emerald-950/45 p-3 backdrop-blur-md"><p className="text-xs text-emerald-100">Verified renewable producer</p><h2 className="mt-1 text-lg font-semibold">{listing.name}</h2></div></div><div className="p-5"><div className="flex items-center justify-between gap-3 text-sm"><p className="flex items-center gap-1 text-[var(--muted)]"><MapPin className="h-4 w-4"/>{listing.location}</p>{listing.verified&&<span className="flex items-center gap-1 text-xs font-semibold text-emerald-700"><ShieldCheck className="h-4 w-4"/>Oracle verified</span>}</div><div className="mt-5 grid grid-cols-2 gap-3 rounded-2xl bg-black/[.025] p-3 dark:bg-white/[.04]"><div><span className="text-[11px] text-[var(--muted)]">Market price</span><strong className="block text-lg font-semibold">{formatMoney(listing.price)}/kWh</strong></div><div><span className="text-[11px] text-[var(--muted)]">Available</span><strong className="block text-lg font-semibold">{listing.available.toLocaleString()} kWh</strong></div><div><span className="text-[11px] text-[var(--muted)]">Delivery</span><strong className="block text-sm font-semibold">{listing.delivery??"Today"}</strong></div><div><span className="text-[11px] text-[var(--muted)]">Distance</span><strong className="block text-sm font-semibold">{formatDistance(listing.distanceKm??12.4)}</strong></div></div><p className="mt-4 flex items-center gap-2 text-xs text-emerald-700"><Sparkles className="h-4 w-4"/>{listing.carbonIntensity??24} gCO₂/kWh · Very low carbon</p><Button onClick={()=>onReview?.(listing)} className="mt-5 w-full justify-center"><Zap className="h-4 w-4"/>Review order</Button></div></article>
}
