"use client";
import { useMemo, useState } from "react";
import { Activity, ArrowRight, BarChart3, Filter, Leaf, Map, ShieldCheck, X, Zap } from "lucide-react";
import { energyListings } from "@/data/marketplace";
import { ListingCard, type EnergyListing } from "./listing-card";
import { Button, ButtonLink } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { usePreferences } from "@/context/preferences-context";
export function MarketplaceWorkspace(){
 const [source,setSource]=useState("All"); const [selected,setSelected]=useState<EnergyListing|null>(null); const [verifiedOnly,setVerifiedOnly]=useState(false); const {formatMoney}=usePreferences();
 const filtered=useMemo(()=>energyListings.filter(x=>(source==="All"||x.source===source)&&(!verifiedOnly||x.verified)),[source,verifiedOnly]);
 return <div className="content-container space-y-6">
  <section className="market-hero"><div className="relative z-10 grid gap-6 xl:grid-cols-[1.4fr_.8fr]"><div><Badge className="border-white/20 bg-white/10 text-white">PowerChain Energy Exchange</Badge><h1 className="mt-4 max-w-3xl text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Trade verified renewable energy with transparent delivery and settlement.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-emerald-50/80">Discover local generation, compare carbon intensity, reserve capacity and settle through PowerChain treasury.</p><div className="mt-6 flex flex-wrap gap-3"><Button onClick={()=>setSelected(filtered[0]??null)} className="bg-white text-emerald-950 hover:bg-emerald-50">Buy energy</Button><ButtonLink href="/exchange?create=listing" variant="framed" className="border-white/30 text-white hover:bg-white/10">Create listing</ButtonLink></div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 xl:grid-cols-2"><Kpi label="Live market" value="24.68 GW"/><Kpi label="24h volume" value="1.24 MWh"/><Kpi label="Average price" value="$0.068"/><Kpi label="CO₂ avoided" value="482.6 t"/></div></div></section>
  <section className="grid gap-6 2xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-5"><div className="panel flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-2">{["All","Solar","Wind","Hydro"].map(x=><button key={x} onClick={()=>setSource(x)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${source===x?"bg-emerald-900 text-white":"border border-[var(--border)] bg-[var(--surface)]"}`}>{x}</button>)}</div><Button onClick={()=>setVerifiedOnly((value)=>!value)} aria-pressed={verifiedOnly} variant="framed"><Filter className="h-4 w-4"/>{verifiedOnly?"Verified only":"Filters"}</Button></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-2">{filtered.map(x=><ListingCard key={x.id} listing={x} onReview={setSelected}/>)}</div></div>
   <aside className="space-y-5"><section className="panel overflow-hidden"><div className="market-card-image relative h-56"><div className="absolute inset-0 grid place-items-center"><Map className="h-14 w-14 text-white/80"/></div><div className="absolute left-[28%] top-[34%] h-4 w-4 rounded-full border-4 border-white bg-emerald-500 shadow-lg"/><div className="absolute right-[24%] top-[52%] h-4 w-4 rounded-full border-4 border-white bg-amber-400 shadow-lg"/></div><div className="p-5"><h2 className="font-semibold">Live energy map</h2><p className="mt-1 text-sm text-[var(--muted)]">Nearby verified producers and grid delivery zones.</p><ButtonLink href="/map" variant="framed" className="mt-4 w-full">Open wayfinder <ArrowRight className="h-4 w-4"/></ButtonLink></div></section><section className="review-order"><h2 className="font-semibold">Market intelligence</h2><ul className="mt-4 space-y-3 text-sm"><Insight icon={BarChart3} text="Solar offers are 4.2% below the regional average."/><Insight icon={Activity} text="Delivery capacity is stable for the next 24 hours."/><Insight icon={Leaf} text="Current mix is 96% renewable."/></ul></section></aside>
  </section>
  {selected&&<div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/55 p-4 backdrop-blur-sm" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><section role="dialog" aria-modal="true" aria-label="Review energy order" className="w-full max-w-lg rounded-[28px] border border-white/20 bg-[var(--surface)] p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-emerald-700">Review order</p><h2 className="mt-1 text-2xl font-semibold">{selected.name}</h2></div><button className="icon-button" onClick={()=>setSelected(null)} aria-label="Close order review"><X className="h-5 w-5"/></button></div><div className="mt-6 grid grid-cols-2 gap-4 rounded-2xl bg-black/[.03] p-4 dark:bg-white/[.04]"><OrderLine label="Energy" value="500 kWh"/><OrderLine label="Price" value={`${formatMoney(selected.price)}/kWh`}/><OrderLine label="Subtotal" value={formatMoney(selected.price*500)}/><OrderLine label="Network fee" value={formatMoney(selected.price*500*.012)}/></div><div className="mt-5 flex items-center gap-2 rounded-2xl border border-emerald-700/15 bg-emerald-500/[.06] p-4 text-sm"><ShieldCheck className="h-5 w-5 text-emerald-700"/>Smart-meter availability and grid delivery will be verified before signature.</div><ButtonLink href={`/checkout?listing=${encodeURIComponent(selected.slug)}&amount=500`} className="mt-5 w-full">Continue to signature</ButtonLink></section></div>}
 </div>
}
function Kpi({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/15 bg-white/[.08] p-4 backdrop-blur"><p className="text-[11px] uppercase tracking-wider text-emerald-100/70">{label}</p><strong className="mt-2 block text-xl font-semibold">{value}</strong></div>}
function Insight({icon:Icon,text}:{icon:typeof Activity;text:string}){return <li className="flex gap-3"><Icon className="mt-0.5 h-4 w-4 shrink-0 text-emerald-700"/><span>{text}</span></li>}
function OrderLine({label,value}:{label:string;value:string}){return <div><p className="text-xs text-[var(--muted)]">{label}</p><strong className="mt-1 block font-semibold">{value}</strong></div>}
