import { EnergyInvariantError, activeReservationWh, assertBatchCanIssuePosition, assertPositionAllocation, economicallyBackedWh, parseWh, positionAvailableWh, stableStringify, transitionEnergyPosition, type EnergyBatch, type EnergyPosition, type EnergyProof, type EnergyReservation, type EnergyRetirement, type EnergyRetirementReason, type EnergyWh } from "@powerchain/energy-core";
import { activeRepresentedWh, assertCanRetirePosition, assertRepresentationBacked, createPet20Metadata, explorerUrl, representationCoveragePpm, type ChainRepresentation, type EnergyRwaRecord, type EnergyRepresentationNetwork } from "@powerchain/energy-rwa";
import { buildEnergyAssetGraph, type AssetGraph } from "@powerchain/asset-graph";

export const DIGITAL_ENERGY_OS_VERSION = "1.0.0" as const;
export type DigitalEnergyDataMode = "DEMO" | "LIVE" | "DEGRADED";
export interface DigitalEnergySummary {
  organizationId:string; canonicalUnit:"Wh"; dataMode:DigitalEnergyDataMode;
  verifiedWh:EnergyWh; availableWh:EnergyWh; activePositionWh:EnergyWh; reservedWh:EnergyWh; representedWh:EnergyWh; representedSolanaWh:EnergyWh; representedSuiWh:EnergyWh; retiredWh:EnergyWh;
  representationCoveragePpm:bigint; verifiedToPositionCoveragePpm:bigint; batches:number; positions:number; rwaAssets:number;
}
export interface DigitalEnergySystemState { version:typeof DIGITAL_ENERGY_OS_VERSION; physicalEnergyAuthoritative:true; canonicalUnit:"Wh"; energyRwaStandard:"PET-20 v1.0.0"; networks:{solana:{role:"PRIMARY_EXECUTION";asset:"PWRC";explorer:"SOLSCAN"};sui:{role:"SECONDARY_OBJECT_ENVIRONMENT";asset:"wPWRC";explorer:"SUISCAN"}}; operations:{digitalTwin:true;delivery:true;reconciliation:true;financialSettlement:true}; authorityBoundaries:{meterEvidenceRequiredForDelivery:true;financialSettlementDoesNotProveDelivery:true;blockchainConfirmationDoesNotCreateEnergy:true}; runtimeSafety:{unsafeMainnetMockWritesRejected:true; offlineEconomicWrites:"REVIEW_ONLY"}; }
export interface DigitalEnergySnapshot { summary:DigitalEnergySummary; proofs:EnergyProof[]; batches:EnergyBatch[]; positions:EnergyPosition[]; rwas:EnergyRwaRecord[]; assetGraph:AssetGraph; system:DigitalEnergySystemState; }

function nowAt(value:string){return new Date(value)}
export function createDemoDigitalEnergySnapshot(organizationId="org_powerchain_demo"):DigitalEnergySnapshot{
  const proofs:EnergyProof[]=[
    {id:"proof_hel_001",organizationId,siteId:"site_helsinki_solar",meterId:"meter_hel_01",meteringPointId:"mp_hel_01",source:"SOLAR",measuredWh:14380n,verifiedWh:14210n,intervalStart:nowAt("2026-08-23T10:00:00.000Z"),intervalEnd:nowAt("2026-08-23T11:00:00.000Z"),qualityScorePpm:989000n,evidenceRoot:"ev_hel_20260823_10",verifier:"powerchain-meter-verifier",verificationVersion:"1.0.0",state:"VERIFIED"},
    {id:"proof_esp_001",organizationId,siteId:"site_espoo_wind",meterId:"meter_esp_01",meteringPointId:"mp_esp_01",source:"WIND",measuredWh:26000000n,verifiedWh:25000000n,intervalStart:nowAt("2026-08-23T10:00:00.000Z"),intervalEnd:nowAt("2026-08-23T11:00:00.000Z"),qualityScorePpm:997000n,evidenceRoot:"ev_esp_20260823_10",verifier:"powerchain-meter-verifier",verificationVersion:"1.0.0",state:"VERIFIED"},
  ];
  const batches:EnergyBatch[]=[
    {id:"batch_hel_001",organizationId,siteId:"site_helsinki_solar",gridAreaId:"FI-HELSINKI-FEEDER-07",source:"SOLAR",intervalStart:proofs[0]!.intervalStart,intervalEnd:proofs[0]!.intervalEnd,measuredWh:14380n,verifiedWh:14210n,invalidatedWh:0n,retiredWh:0n,state:"FINALIZED",evidenceRoot:proofs[0]!.evidenceRoot,proofIds:[proofs[0]!.id]},
    {id:"batch_esp_001",organizationId,siteId:"site_espoo_wind",gridAreaId:"FI-ESPOO-FEEDER-12",source:"WIND",intervalStart:proofs[1]!.intervalStart,intervalEnd:proofs[1]!.intervalEnd,measuredWh:26000000n,verifiedWh:25000000n,invalidatedWh:0n,retiredWh:2000000n,state:"FINALIZED",evidenceRoot:proofs[1]!.evidenceRoot,proofIds:[proofs[1]!.id]},
  ];
  const positions:EnergyPosition[]=[
    {id:"ep_hel_8310",organizationId,energyBatchId:"batch_hel_001",ownerId:"org_powerchain_demo",source:"SOLAR",amountWh:8310n,state:"RESERVED",gridAreaId:"FI-HELSINKI-FEEDER-07",intervalStart:batches[0]!.intervalStart,intervalEnd:batches[0]!.intervalEnd,evidenceRoot:batches[0]!.evidenceRoot,createdAt:nowAt("2026-08-23T11:02:00.000Z"),updatedAt:nowAt("2026-08-23T11:05:00.000Z")},
    {id:"ep_esp_25m",organizationId,energyBatchId:"batch_esp_001",ownerId:"org_powerchain_demo",source:"WIND",amountWh:20000000n,state:"AVAILABLE",gridAreaId:"FI-ESPOO-FEEDER-12",intervalStart:batches[1]!.intervalStart,intervalEnd:batches[1]!.intervalEnd,evidenceRoot:batches[1]!.evidenceRoot,createdAt:nowAt("2026-08-23T11:03:00.000Z"),updatedAt:nowAt("2026-08-23T11:03:00.000Z")},
  ];
  const helReservations:EnergyReservation[]=[{id:"res_hel_market_001",organizationId,energyPositionId:"ep_hel_8310",amountWh:1000n,purpose:"LOCAL_MARKET",state:"ACTIVE",createdAt:nowAt("2026-08-23T11:04:00.000Z"),updatedAt:nowAt("2026-08-23T11:04:00.000Z")}];
  const helRepresentations:ChainRepresentation[]=[{id:"rep_hel_sol_001",organizationId,energyPositionId:"ep_hel_8310",network:"SOLANA",reference:"5N7vPowerChainEnergyPositionDemo111111111111111",amountWh:5000n,state:"ACTIVE",metadataStandard:"1.0.0",createdAt:nowAt("2026-08-23T11:05:00.000Z"),updatedAt:nowAt("2026-08-23T11:05:00.000Z")}];
  const espRepresentations:ChainRepresentation[]=[{id:"rep_esp_sui_001",organizationId,energyPositionId:"ep_esp_25m",network:"SUI",reference:"0x8fd31a2c5b007d1374b1e6f4e12d09b5ca9fc9b63e35c8c6d19b22104c128001",amountWh:15000000n,state:"ACTIVE",metadataStandard:"1.0.0",createdAt:nowAt("2026-08-23T11:06:00.000Z"),updatedAt:nowAt("2026-08-23T11:06:00.000Z")}];
  const rwas:EnergyRwaRecord[]=[
    {id:"rwa_ep_hel_8310",organizationId,position:positions[0]!,metadata:createPet20Metadata(positions[0]!),representations:helRepresentations,reservations:helReservations,retirements:[],createdAt:positions[0]!.createdAt,updatedAt:positions[0]!.updatedAt},
    {id:"rwa_ep_esp_25m",organizationId,position:positions[1]!,metadata:createPet20Metadata(positions[1]!),representations:espRepresentations,reservations:[],retirements:[],createdAt:positions[1]!.createdAt,updatedAt:positions[1]!.updatedAt},
  ];
  for(const record of rwas)assertRepresentationBacked(record);
  const summary=calculateDigitalEnergySummary({organizationId,batches,positions,rwas,dataMode:"DEMO"});
  return{summary,proofs,batches,positions,rwas,assetGraph:buildEnergyAssetGraph({organizationId,batches,positions,rwas}),system:systemState()};
}

export function systemState():DigitalEnergySystemState{return{version:DIGITAL_ENERGY_OS_VERSION,physicalEnergyAuthoritative:true,canonicalUnit:"Wh",energyRwaStandard:"PET-20 v1.0.0",networks:{solana:{role:"PRIMARY_EXECUTION",asset:"PWRC",explorer:"SOLSCAN"},sui:{role:"SECONDARY_OBJECT_ENVIRONMENT",asset:"wPWRC",explorer:"SUISCAN"}},operations:{digitalTwin:true,delivery:true,reconciliation:true,financialSettlement:true},authorityBoundaries:{meterEvidenceRequiredForDelivery:true,financialSettlementDoesNotProveDelivery:true,blockchainConfirmationDoesNotCreateEnergy:true},runtimeSafety:{unsafeMainnetMockWritesRejected:true,offlineEconomicWrites:"REVIEW_ONLY"}}}

export function calculateDigitalEnergySummary(input:{organizationId:string;batches:readonly EnergyBatch[];positions:readonly EnergyPosition[];rwas:readonly EnergyRwaRecord[];dataMode:DigitalEnergyDataMode}):DigitalEnergySummary{
  const verifiedWh=input.batches.reduce((sum,b)=>sum+economicallyBackedWh(b)+b.retiredWh,0n);
  const retiredWh=input.batches.reduce((sum,b)=>sum+b.retiredWh,0n);
  const activePositionWh=input.positions.filter(p=>p.state!=="RETIRED").reduce((sum,p)=>sum+p.amountWh,0n);
  const reservedWh=input.rwas.reduce((sum,rwa)=>sum+rwa.reservations.filter(r=>r.state==="ACTIVE").reduce((inner,r)=>inner+r.amountWh,0n),0n);
  const representedWh=input.rwas.reduce((sum,rwa)=>sum+activeRepresentedWh(rwa.representations),0n);
  const representedSolanaWh=input.rwas.reduce((sum,rwa)=>sum+rwa.representations.filter(r=>r.network==="SOLANA"&&r.state!=="RETIRED").reduce((inner,r)=>inner+r.amountWh,0n),0n);
  const representedSuiWh=input.rwas.reduce((sum,rwa)=>sum+rwa.representations.filter(r=>r.network==="SUI"&&r.state!=="RETIRED").reduce((inner,r)=>inner+r.amountWh,0n),0n);
  const availableWh=input.batches.reduce((sum,batch)=>{const issued=input.positions.filter(p=>p.energyBatchId===batch.id&&p.state!=="RETIRED").reduce((inner,p)=>inner+p.amountWh,0n);const backed=economicallyBackedWh(batch);return sum+(backed>issued?backed-issued:0n)},0n);
  return{organizationId:input.organizationId,canonicalUnit:"Wh",dataMode:input.dataMode,verifiedWh,availableWh,activePositionWh,reservedWh,representedWh,representedSolanaWh,representedSuiWh,retiredWh,representationCoveragePpm:activePositionWh===0n?0n:representedWh*1_000_000n/activePositionWh,verifiedToPositionCoveragePpm:verifiedWh===0n?0n:activePositionWh*1_000_000n/verifiedWh,batches:input.batches.length,positions:input.positions.length,rwaAssets:input.rwas.length};
}

export interface DigitalEnergyPositionBacking {
  positionId:string; canonicalPositionWh:EnergyWh; activeReservedWh:EnergyWh; activeRepresentedWh:EnergyWh; representedSolanaWh:EnergyWh; representedSuiWh:EnergyWh; retiredWh:EnergyWh; availableWh:EnergyWh; representationCoveragePpm:bigint; invariantState:"BACKED";
}

export function calculatePositionBacking(record:EnergyRwaRecord):DigitalEnergyPositionBacking{
  const activeReserved=activeReservationWh(record.reservations);
  const represented=activeRepresentedWh(record.representations);
  const representedSolana=record.representations.filter(r=>r.network==="SOLANA"&&r.state!=="RETIRED").reduce((sum,r)=>sum+r.amountWh,0n);
  const representedSui=record.representations.filter(r=>r.network==="SUI"&&r.state!=="RETIRED").reduce((sum,r)=>sum+r.amountWh,0n);
  const retired=record.retirements.reduce((sum,r)=>sum+r.amountWh,0n);
  const available=positionAvailableWh({position:record.position,reservations:record.reservations,representedWh:represented,retiredWh:retired});
  assertRepresentationBacked(record);
  return{positionId:record.position.id,canonicalPositionWh:record.position.amountWh,activeReservedWh:activeReserved,activeRepresentedWh:represented,representedSolanaWh:representedSolana,representedSuiWh:representedSui,retiredWh:retired,availableWh:available,representationCoveragePpm:representationCoveragePpm(record),invariantState:"BACKED"};
}

export class DigitalEnergyMemoryStore{
  private proofs=new Map<string,EnergyProof>(); private batches=new Map<string,EnergyBatch>(); private positions=new Map<string,EnergyPosition>(); private rwas=new Map<string,EnergyRwaRecord>(); private idempotency=new Map<string,unknown>();
  constructor(snapshot:DigitalEnergySnapshot){snapshot.proofs.forEach(v=>this.proofs.set(v.id,v));snapshot.batches.forEach(v=>this.batches.set(v.id,v));snapshot.positions.forEach(v=>this.positions.set(v.id,v));snapshot.rwas.forEach(v=>this.rwas.set(v.id,v))}
  snapshot(organizationId:string,dataMode:DigitalEnergyDataMode="DEMO"):DigitalEnergySnapshot{const proofs=[...this.proofs.values()].filter(v=>v.organizationId===organizationId);const batches=[...this.batches.values()].filter(v=>v.organizationId===organizationId);const positions=[...this.positions.values()].filter(v=>v.organizationId===organizationId);const rwas=[...this.rwas.values()].filter(v=>v.organizationId===organizationId);return{summary:calculateDigitalEnergySummary({organizationId,batches,positions,rwas,dataMode}),proofs,batches,positions,rwas,assetGraph:buildEnergyAssetGraph({organizationId,batches,positions,rwas}),system:systemState()}}
  private once<T>(organizationId:string,scope:string,key:string,action:()=>T):T{const scoped=`${organizationId}:${scope}:${key}`;if(this.idempotency.has(scoped))return this.idempotency.get(scoped) as T;const value=action();this.idempotency.set(scoped,value);return value}
  createPosition(input:{organizationId:string;id:string;batchId:string;ownerId:string;amountWh:string;idempotencyKey:string}):EnergyPosition{return this.once(input.organizationId,"position:create",input.idempotencyKey,()=>{const batch=this.batches.get(input.batchId);if(!batch||batch.organizationId!==input.organizationId)throw new EnergyInvariantError("ENERGY_BATCH_NOT_FOUND","Energy Batch not found");const amountWh=parseWh(input.amountWh);const activeWh=[...this.positions.values()].filter(p=>p.organizationId===input.organizationId&&p.energyBatchId===batch.id&&p.state!=="RETIRED").reduce((sum,p)=>sum+p.amountWh,0n);assertBatchCanIssuePosition(batch,activeWh,amountWh);const now=new Date();const position:EnergyPosition={id:input.id,organizationId:input.organizationId,energyBatchId:batch.id,ownerId:input.ownerId,source:batch.source,amountWh,state:"AVAILABLE",...(batch.gridAreaId?{gridAreaId:batch.gridAreaId}:{}),intervalStart:batch.intervalStart,intervalEnd:batch.intervalEnd,evidenceRoot:batch.evidenceRoot,createdAt:now,updatedAt:now};this.positions.set(position.id,position);const rwa:EnergyRwaRecord={id:`rwa_${position.id}`,organizationId:input.organizationId,position,metadata:createPet20Metadata(position),representations:[],reservations:[],retirements:[],createdAt:now,updatedAt:now};this.rwas.set(rwa.id,rwa);return position})}
  reserve(input:{organizationId:string;positionId:string;reservationId:string;amountWh:string;purpose:string;idempotencyKey:string}):EnergyReservation{return this.once(input.organizationId,`position:${input.positionId}:reserve`,input.idempotencyKey,()=>{const rwa=this.getRwaByPosition(input.organizationId,input.positionId);const amountWh=parseWh(input.amountWh);assertPositionAllocation({position:rwa.position,reservations:rwa.reservations,representedWh:activeRepresentedWh(rwa.representations),retiredWh:rwa.retirements.reduce((s,r)=>s+r.amountWh,0n),requestedWh:amountWh});const now=new Date();const reservation:EnergyReservation={id:input.reservationId,organizationId:input.organizationId,energyPositionId:input.positionId,amountWh,purpose:input.purpose,state:"ACTIVE",createdAt:now,updatedAt:now};rwa.reservations.push(reservation);rwa.position={...rwa.position,state:transitionEnergyPosition(rwa.position.state,"RESERVED"),updatedAt:now};this.positions.set(rwa.position.id,rwa.position);rwa.updatedAt=now;return reservation})}
  releaseReservation(input:{organizationId:string;reservationId:string;idempotencyKey:string}):EnergyReservation{return this.once(input.organizationId,`reservation:${input.reservationId}:release`,input.idempotencyKey,()=>{for(const rwa of this.rwas.values()){const index=rwa.reservations.findIndex(r=>r.id===input.reservationId&&r.organizationId===input.organizationId);if(index>=0){const current=rwa.reservations[index]!;if(current.state==="RELEASED")return current;if(current.state!=="ACTIVE")throw new EnergyInvariantError("RESERVATION_NOT_ACTIVE","Only active reservations can be released");const now=new Date();const updated={...current,state:"RELEASED" as const,updatedAt:now};rwa.reservations[index]=updated;if(!rwa.reservations.some(r=>r.state==="ACTIVE")&&rwa.position.state==="RESERVED"){rwa.position={...rwa.position,state:transitionEnergyPosition(rwa.position.state,"AVAILABLE"),updatedAt:now};this.positions.set(rwa.position.id,rwa.position)}rwa.updatedAt=now;return updated}}throw new EnergyInvariantError("ENERGY_RESERVATION_NOT_FOUND","Energy reservation not found")})}
  positionBacking(organizationId:string,positionId:string):DigitalEnergyPositionBacking{return calculatePositionBacking(this.getRwaByPosition(organizationId,positionId))}
  represent(input:{organizationId:string;positionId:string;representationId:string;network:EnergyRepresentationNetwork;reference:string;amountWh:string;idempotencyKey:string}):ChainRepresentation{return this.once(input.organizationId,`position:${input.positionId}:represent`,input.idempotencyKey,()=>{const rwa=this.getRwaByPosition(input.organizationId,input.positionId);const amountWh=parseWh(input.amountWh);assertRepresentationBacked(rwa,amountWh);const now=new Date();const representation:ChainRepresentation={id:input.representationId,organizationId:input.organizationId,energyPositionId:input.positionId,network:input.network,reference:input.reference,amountWh,state:"ACTIVE",metadataStandard:"1.0.0",createdAt:now,updatedAt:now};rwa.representations.push(representation);assertRepresentationBacked(rwa);rwa.updatedAt=now;return representation})}
  retireRepresentation(input:{organizationId:string;representationId:string;idempotencyKey:string}):ChainRepresentation{return this.once(input.organizationId,`representation:${input.representationId}:retire`,input.idempotencyKey,()=>{for(const rwa of this.rwas.values()){const index=rwa.representations.findIndex(r=>r.id===input.representationId&&r.organizationId===input.organizationId);if(index>=0){const current=rwa.representations[index]!;if(current.state==="RETIRED")return current;const updated={...current,state:"RETIRED" as const,updatedAt:new Date()};rwa.representations[index]=updated;rwa.updatedAt=updated.updatedAt;return updated}}throw new EnergyInvariantError("CHAIN_REPRESENTATION_NOT_FOUND","Chain representation not found")})}
  retirePosition(input:{organizationId:string;positionId:string;retirementId:string;reason:EnergyRetirementReason;idempotencyKey:string}):EnergyRetirement{return this.once(input.organizationId,`position:${input.positionId}:retire`,input.idempotencyKey,()=>{const rwa=this.getRwaByPosition(input.organizationId,input.positionId);assertCanRetirePosition(rwa);if(rwa.reservations.some(r=>r.state==="ACTIVE"))throw new EnergyInvariantError("ACTIVE_RESERVATIONS_MUST_RELEASE_FIRST","Release active reservations before retirement");const existingRetired=rwa.retirements.reduce((sum,r)=>sum+r.amountWh,0n);const remaining=rwa.position.amountWh-existingRetired;if(remaining<=0n)throw new EnergyInvariantError("ENERGY_POSITION_ALREADY_RETIRED","Energy Position is already fully retired");const now=new Date();const retirement:EnergyRetirement={id:input.retirementId,organizationId:input.organizationId,energyPositionId:input.positionId,amountWh:remaining,reason:input.reason,retiredAt:now};rwa.retirements.push(retirement);rwa.position={...rwa.position,state:transitionEnergyPosition(rwa.position.state,"RETIRED"),updatedAt:now};rwa.updatedAt=now;this.positions.set(rwa.position.id,rwa.position);const batch=this.batches.get(rwa.position.energyBatchId);if(batch)this.batches.set(batch.id,{...batch,retiredWh:batch.retiredWh+remaining});return retirement})}
  getRwaByPosition(organizationId:string,positionId:string):EnergyRwaRecord{const rwa=[...this.rwas.values()].find(value=>value.organizationId===organizationId&&value.position.id===positionId);if(!rwa)throw new EnergyInvariantError("ENERGY_RWA_NOT_FOUND","Energy RWA not found");return rwa}
}

export function serializeDigitalEnergy<T>(value:T):unknown{return JSON.parse(stableStringify(value))}
export { explorerUrl, representationCoveragePpm } from "@powerchain/energy-rwa";
