export type AiProviderKind="powerchain"|"user"|"organization";
export type AiProtocol="openai-compatible"|"anthropic-compatible"|"custom-rest"|"local";
export interface ModelCapabilities{chat:boolean;vision:boolean;audio:boolean;tools:boolean;json:boolean;embeddings:boolean;reasoning:boolean;streaming:boolean}
export interface GridLlmConfig{id:string;name:string;provider:AiProviderKind;modelId:string;contextWindow:number;maxOutputTokens:number;temperature:number;topP:number;frequencyPenalty?:number;presencePenalty?:number;stopSequences?:string[];systemPromptId?:string;memoryConfigId?:string;loraAdapterId?:string;toolsEnabled:boolean;streamingEnabled:boolean;structuredOutputEnabled:boolean;pricingMode:"platform-credits"|"user-provider"|"hybrid";capabilities:ModelCapabilities}
export interface AiProviderConnection{id:string;ownerId:string;name:string;protocol:AiProtocol;baseUrl:string;encryptedCredentialId?:string;organizationId?:string;defaultModel?:string;status:"active"|"invalid"|"disabled";lastValidatedAt?:string}
export interface AgentToolPermission{tool:string;scopes:string[];approvalRequired:boolean}
export interface AiAgent{id:string;name:string;description:string;version:string;modelConfigId:string;systemPromptId:string;memoryConfigId?:string;loraAdapterId?:string;tools:AgentToolPermission[];knowledgeSourceIds:string[];maxSteps:number;timeoutMs:number;spendingLimitUsd?:number;status:"draft"|"published"|"archived"}
export interface PromptVariable{name:string;description?:string;required:boolean;defaultValue?:string}
export interface PromptTemplate{id:string;slug:string;name:string;description?:string;version:string;systemTemplate?:string;userTemplate:string;variables:PromptVariable[];tags:string[];ownerId:string;visibility:"private"|"organization"|"public";status:"draft"|"published"|"archived"}
export interface MemoryConfig{id:string;scope:"conversation"|"user"|"agent"|"workspace";enabled:boolean;strategy:"window"|"summary"|"vector"|"hybrid";maxItems?:number;maxTokens?:number;ttlSeconds?:number;userEditable:boolean;requireConsent:boolean}
export interface LoraAdapter{id:string;name:string;version:string;baseModelId:string;storageUri:string;checksum:string;rank?:number;alpha?:number;ownerId:string;visibility:"private"|"organization"|"public";status:"uploading"|"validating"|"ready"|"failed"}
export interface AiUsageQuote{quoteId:string;estimatedUsd:string;pwrcUsdPrice:string;estimatedPwrc:string;expiresAt:string}
export interface AiUsageSettlement{requestId:string;quoteId:string;inputTokens:number;outputTokens:number;cachedTokens?:number;toolCalls?:number;providerCostUsd:string;platformFeeUsd:string;totalCostUsd:string;pwrcUsdPrice:string;pwrcCharged:string;pricingSnapshotId:string;settledAt:string}
export const gridLlmDefault:GridLlmConfig={id:"gridllm-energy",name:"GridLLM Energy",provider:"powerchain",modelId:"gridllm-8b-energy",contextWindow:32768,maxOutputTokens:2048,temperature:.2,topP:.9,systemPromptId:"powerchain-energy",memoryConfigId:"workspace-memory",loraAdapterId:"renewables-lora",toolsEnabled:true,streamingEnabled:true,structuredOutputEnabled:true,pricingMode:"platform-credits",capabilities:{chat:true,vision:false,audio:false,tools:true,json:true,embeddings:true,reasoning:true,streaming:true}};
