import fs from "node:fs"; import path from "node:path"; import {fileURLToPath} from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."); const errors=[]; const required=["README.md","apps/energy","apps/energy/app/energy","apps/energy/app/assets","apps/energy/app/devices","apps/docs","apps/platform","apps/admin","apps/mapper","apps/api","apps/worker","apps/companies","apps/grid","apps/plants","apps/wind","apps/charging","apps/supply-chain","apps/api/api/openapi.yaml","apps/api/api/postman/PowerChain-Local-Energy-OS.postman_collection.json","apps/api/api/postman/PowerChain-Local.postman_environment.json","packages/shared","packages/ui","packages/energy-core","packages/energy-rwa","packages/pwrc","packages/saas","packages/protocols","packages/auth","packages/validation","packages/policy","packages/events","packages/audit","packages/metering","packages/telemetry","packages/settlement","packages/ledger","packages/rewards","store/package.json","storage/package.json","programs/README.md","programs/energy-rwa","programs/energy-rwa/README.md","move/powerchain","prisma.config.ts","prisma/schema.prisma","components/docs","storage/src/index.ts","store/src/index.ts","docs/DOCS-APP.md","docs/STORAGE.md","docs/STATE-MANAGEMENT.md","docs/DESIGN-SYSTEM.md","docs/ARCHITECTURE.md","docs/SAAS.md","docs/API.md","docs/ASSETS.md","docs/FULLSTACK.md","docs/AUTHENTICATION.md","docs/SECURITY.md","docs/DATA-PLANE.md","docs/RELEASE.md","supabase/migrations/002_tenant_rls.sql"];
for(const r of required) if(!fs.existsSync(path.join(root,r))) errors.push(`missing:${r}`);
const packageFiles=[]; function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){if(["node_modules",".next",".git"].includes(e.name))continue; const p=path.join(d,e.name); if(e.isDirectory())walk(p); else if(e.name==="package.json")packageFiles.push(p)}} walk(root);
const names=new Map(), workspaceNames=new Set(); const manifests=[]; for(const p of packageFiles){const o=JSON.parse(fs.readFileSync(p,"utf8"));manifests.push([p,o]);if(o.version!=="1.0.0")errors.push(`version:${path.relative(root,p)}:${o.version}`);if(o.name){if(names.has(o.name))errors.push(`duplicate-package:${o.name}`);names.set(o.name,p);workspaceNames.add(o.name)}}
for(const [p,o] of manifests){for(const group of ["dependencies","devDependencies","peerDependencies"]){for(const [name,v] of Object.entries(o[group]??{})){if(String(v).startsWith("workspace:") && !workspaceNames.has(name))errors.push(`missing-workspace-dependency:${path.relative(root,p)}:${name}`)}}}
const units=fs.readFileSync(path.join(root,"packages/energy-core/src/index.ts"),"utf8"); for(const s of ["KWH = 1_000n","MWH = 1_000_000n","GWH = 1_000_000_000n"]) if(!units.includes(s)) errors.push(`energy-unit:${s}`);
const env=fs.readFileSync(path.join(root,".env.example"),"utf8"); for(const secret of ["SUPABASE_SERVICE_ROLE_KEY","BETTER_AUTH_SECRET","HELIUS_API_KEY"]){if(env.includes(`NEXT_PUBLIC_${secret}`))errors.push(`public-secret:${secret}`)}

const rootManifest=JSON.parse(fs.readFileSync(path.join(root,"package.json"),"utf8")); if(!rootManifest.scripts?.["local-energy:verify"])errors.push("missing-script:local-energy:verify");
const workspace=fs.readFileSync(path.join(root,"pnpm-workspace.yaml"),"utf8"); for(const dep of ["@prisma/engines","esbuild","prisma"]){if(!workspace.includes(`${dep}: true`) && !workspace.includes(`'${dep}': true`))errors.push(`unapproved-build:${dep}`)}
const prismaSchema=fs.readFileSync(path.join(root,"prisma/schema.prisma"),"utf8"); if(!prismaSchema.includes('provider = "prisma-client"')||!prismaSchema.includes('output   = "../packages/database/src/generated/prisma"'))errors.push("prisma7-generator"); if(/url\s*=\s*env\(/.test(prismaSchema)||/directUrl\s*=/.test(prismaSchema))errors.push("prisma7-datasource-config");
if(!fs.existsSync(path.join(root,"apps/api/app/api/v1")))errors.push("missing:/api/v1");
for(const route of ["energy-proofs","energy-batches","energy-positions","energy-reservations","energy-retirements"]){const src=fs.readFileSync(path.join(root,`apps/api/app/api/v1/${route}/route.ts`),"utf8");if(!src.includes("export async function POST"))errors.push(`missing-economic-mutation:${route}`);if(src.includes("items:[]"))errors.push(`stub-economic-route:${route}`)}
for(const model of ["IdempotencyRecord","AuditLog","DomainEventOutbox","EnergySite","Meter","PowerPlant","WindFarm","ChargingStation","ChargingSession","AssetPassport"]){if(!prismaSchema.includes(`model ${model}`))errors.push(`missing-prisma-model:${model}`)}
for(const model of ["User","OrganizationMembership","Session","LinkedWallet","WalletAuthChallenge"]){if(!prismaSchema.includes(`model ${model}`))errors.push(`missing-auth-model:${model}`)}
const authVerify=path.join(root,"apps/api/app/api/v1/auth/solana/verify/route.ts");if(!fs.existsSync(authVerify))errors.push("missing-auth-verify-route");
const rls=fs.readFileSync(path.join(root,"supabase/migrations/002_tenant_rls.sql"),"utf8");if(!rls.includes("powerchain_has_org")||!rls.includes("energy_positions_member_select"))errors.push("tenant-rls-incomplete");
const anchor=fs.readFileSync(path.join(root,"programs/energy-rwa/src/lib.rs"),"utf8");for(const token of ["verification_authority","position_nonce","finalize_batch","UnitAlignment"]){if(!anchor.includes(token))errors.push(`anchor-hardening:${token}`)}
const move=fs.readFileSync(path.join(root,"move/powerchain/sources/energy_position.move"),"utf8");for(const token of ["VerifierCap","finalize_batch","WH_PER_MWH","batch.retired_wh"]){if(!move.includes(token))errors.push(`sui-hardening:${token}`)}

const uiCss=fs.readFileSync(path.join(root,"packages/ui/src/styles.css"),"utf8");if(!uiCss.includes("height:100dvh")||!uiCss.includes("position:fixed"))errors.push("ui-sidebar-not-full-height");if(!uiCss.includes("grid-template-columns:1fr 1fr 76px 1fr 1fr"))errors.push("ui-mobile-dock-not-five-part");if(units.includes("Number(wh)")||units.includes("Number(GWH)")||units.includes("Number(MWH)"))errors.push("energy-display-number-coercion");
const footerTargets=["components/docs/docs-shell.tsx","packages/ui/src/app-shell.tsx"];for(const target of footerTargets){const src=fs.readFileSync(path.join(root,target),"utf8");if(/<footer\b/i.test(src))errors.push(`application-footer:${target}`)}
const pwrc=fs.readFileSync(path.join(root,"packages/pwrc/src/index.ts"),"utf8"); if(!pwrc.includes('PWRC_CHAIN = "SOLANA"')||!pwrc.includes('WPWRC_CHAIN = "SUI"'))errors.push("pwrc-chain-model");
const rwa=fs.readFileSync(path.join(root,"packages/energy-rwa/src/index.ts"),"utf8"); if(!rwa.includes("ENERGY_RWA_OVERISSUANCE") && !fs.readFileSync(path.join(root,"packages/energy-core/src/index.ts"),"utf8").includes("ENERGY_RWA_OVERISSUANCE"))errors.push("rwa-overissuance-guard");
if(errors.length){console.error(JSON.stringify({status:"failed",errors},null,2));process.exit(1)} console.log(JSON.stringify({status:"ok",canonicalVersion:"1.0.0",packages:packageFiles.length,checks:["required-paths","canonical-versions","duplicate-package-names","workspace-dependencies","energy-units","pwrc-sui-model","rwa-supply-guard","api-v1","public-secrets","pnpm-build-allowlist","prisma7-contract","api-docs","economic-mutations","idempotency","audit-outbox","infrastructure-models","session-auth","tenant-rls","anchor-rwa-hardening","sui-rwa-hardening","brand-ui-shell","five-part-mobile-nav","bigint-energy-display","no-application-footer"]},null,2));
