import { IntegrationHero, IntegrationStatusGrid } from "@/components/integrations";
import { integrationDefinitions, type IntegrationHealth } from "@powerchain/integration";
import Link from "next/link";
const health: IntegrationHealth[] = [
 { provider:"pyth", state:"available", checkedAt:new Date().toISOString(), latencyMs:132, circuitState:"closed" },
 { provider:"helius", state:"available", checkedAt:new Date().toISOString(), latencyMs:218, circuitState:"closed" },
 { provider:"cetus", state:"available", checkedAt:new Date().toISOString(), latencyMs:246, circuitState:"closed" },
 { provider:"jupiter", state:"degraded", checkedAt:new Date().toISOString(), errorCode:"RATE_LIMITED", circuitState:"half-open" },
 { provider:"circle", state:"misconfigured", checkedAt:new Date().toISOString(), errorCode:"INVALID_CONFIGURATION", circuitState:"closed" },
 { provider:"helium", state:"unavailable", checkedAt:new Date().toISOString(), errorCode:"PROVIDER_UNAVAILABLE", circuitState:"open" }
];
export default function IntegrationsPage(){ return <main className="content-container space-y-7"><IntegrationHero health={health}/><section><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-emerald-700">Provider catalog</p><h2 className="mt-2 text-2xl font-semibold">Web3, pricing, payment and infrastructure adapters</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">Adapters expose validated operations and explicit failure states. No valid provider response means no live data.</p></div><Link href="/docs/integrations" className="text-sm font-semibold text-emerald-700">Integration documentation →</Link></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{integrationDefinitions.map(item=><article key={item.id} className="rounded-[24px] border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-start justify-between gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-emerald-950 text-sm font-semibold text-white">{item.name.slice(0,2).toUpperCase()}</div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-semibold capitalize text-emerald-800">{item.availability}</span></div><h3 className="mt-5 text-lg font-semibold">{item.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-[var(--muted)]">{item.summary}</p><div className="mt-4 flex flex-wrap gap-2">{item.capabilities.map(cap=><span key={cap} className="rounded-full border border-emerald-800/10 bg-emerald-500/[.06] px-2.5 py-1 text-[11px] font-medium text-emerald-800">{cap}</span>)}</div><Link href={item.documentationPath} className="mt-5 inline-flex text-sm font-semibold text-emerald-700">View integration →</Link></article>)}</div></section><section><h2 className="text-xl font-semibold">Runtime health</h2><p className="mt-1 text-sm text-[var(--muted)]">Provider state, circuit status and latency are displayed without synthetic fallbacks.</p><div className="mt-4"><IntegrationStatusGrid items={health}/></div></section></main>; }
